import Head from 'next/head'
import Image from 'next/image'
import AudioList from '../component/AudioList'
import AudioPlayer from '../component/AudioPlayer'
import MediaControlCard from '../component/Card'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>react audio player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
       <AudioList />
      </main>

     
    </div>
  )
}
